# MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/mangaverse?useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=3156

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cloudinary config (moved from CloudinaryController)
cloudinary.api-key=347182478282281
cloudinary.api-secret=-pNyg-JSTjRu1fgJ0-IwT7QPiGc
cloudinary.cloud-name=dh5yuvk3k
